framework: jest
tier: large
# blocklist:
#   - "./src/newFileTest.test.js##Comparision test"
postMerge:
  pattern: 
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
preMerge:
  pattern:
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
        - node --version
version: 1.0

