---
framework: "jest"
postMerge:
  pattern:
    - "./src/*.test.js"
    - "./src/random.test.js"
preMerge:
  pattern:
    - "./src/*.test.js"
    - "./src/random.test.js"
preRun:
  - npm i
postRun:
  - node --version
  - node --version
version: 2.0
