framework: jest
# blocklist:
#   - "./src/newFileTest.test.js##Comparision test"
tier: large
postMerge:
  pattern: 
    - "./src/*.test.js"
  strategy:
    threshold: 4
    name: after_n_commits
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
preMerge:
  pattern:
    - "./src/*.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 1.0
