---
framework: "jest"
blacklist:
  - 'src/calculator.test.js##Blacklist a test'
postMerge:
  pattern:
    - "./src/*.test.js"
preMerge:
  pattern:
    - "./src/*.test.js"
preRun:
  - npm i
postRun:
  - node --version
version: 2.0
