---
framework: "jest"
blacklist:
  - 'src/calculator.test.js##Blacklist a test'
postMerge:
  pattern:
    - "./src/*.test.js"
preMerge:
  pattern:
    - "./src/*.test.js"
preRun:
  - npm ci
postRun:
  - echo 'Done'
version: 2.0