framework: jest
# blocklist:
#   - "./src/newFileTest.test.js##Comparision tests"
postMerge:
  pattern: 
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
preMerge:
  pattern:
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
nodeVersion: 14.17.2
version: 1.0 

