framework: jest
# blocklist:
#   - "./src/newFileTest.test.js##Comparision tests"
tier: large
postMerge:
  isActive: false
  pattern: 
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
  strategy:
    threshold: 1
    name: after_n_commits
preMerge:
  pattern:
    - "./src/*.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - npm run v
version: 1.0
