framework: jest
# blocklist:
#   - "./src/newFileTest.test.js##Comparision tests"
tier: xsmall
postMerge:
  pattern: 
    - "./src/*.test.js"
  strategy:
    threshold: 1
    name: after_n_commits
preMerge:
  pattern:
    - "./src/*.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 1.0

