framework: jest    
preRun:
  command:
    - npm ci          
postMerge:
  pattern: 
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
preMerge:
  pattern:
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
postRun:
  command:
    - node --version
nodeVersion: 14.17.2
# parallelism: 6
version: 1.0
containerImage: "synapseprivatepullstagetaspoc.azurecr.io/nucleus_private:demo"
