---
framework: jest                  # Mention the testing framework mocha or jest
postMerge:
  pattern:
    - "./src/*.test.js"
preMerge:
  pattern:
    - "./src/*.test.js"
preRun:
  - npm install                   # Mention pre-run steps here
postRun:
  - node --version                # Mention post-run steps here
version: 2.0
